version: '3.4'

services:
  hriswebclient:
    container_name: hriswebclient
    ports:
        - 5101:8080
    build:
        dockerfile: ./Solution/Dockerfile-WebClient
    restart: on-failure

  hriswebapi:
    container_name: hriswebapi
    ports:
        - 5102:8080
    build:
        dockerfile: ./Solution/Dockerfile-WebApi
    restart: on-failure
